language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install
  - cd test
  - npm install
  - npm test
  - cd ..
before_script:
  - npm install
scripts:
  - "start": "node web-server.js",
deploy:
  provider: heroku
  api_key: fa60f88e-abe4-496d-aa9f-dd8e158151a6
  app: angularjs-todomvc-lobinhaxd
